#!/usr/bin/env python3
from __future__ import annotations

import json
import shutil
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]


def read_jsonl(path: Path, cap: int | None = None) -> list[dict]:
    if not path.exists():
        return []
    rows = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.strip():
            rows.append(json.loads(line))
            if cap and len(rows) >= cap:
                break
    return rows


def write_jsonl(path: Path, rows: list[dict]) -> int:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, ensure_ascii=False, sort_keys=True) + "\n")
    return len(rows)


def build_uk() -> dict[str, int]:
    out = ROOT / "data/processed/final/uk"
    ext = ROOT / "data/processed/external/uk"
    counts = {}
    counts["mt_train_final"] = write_jsonl(out / "mt_train_final.jsonl", read_jsonl(ext / "mt_train.jsonl") + read_jsonl(ext / "mt_doc_train.jsonl"))
    counts["qa_train_final"] = write_jsonl(out / "qa_train_final.jsonl", read_jsonl(ROOT / "data/processed/uk/qa_train.jsonl") + read_jsonl(ext / "qa_generated_public.jsonl", 2000))
    counts["sc_train_final"] = write_jsonl(out / "sc_train_final.jsonl", read_jsonl(ROOT / "data/processed/uk/sc_train.jsonl") + read_jsonl(ext / "sc_real.jsonl") + read_jsonl(ext / "sc_synthetic_public.jsonl"))
    counts["gc_train_final"] = write_jsonl(out / "gc_train_final.jsonl", read_jsonl(ROOT / "data/processed/uk/gc_train.jsonl") + read_jsonl(ext / "gc_real.jsonl") + read_jsonl(ext / "gc_synthetic_public.jsonl"))
    counts["mr_train_final"] = write_jsonl(out / "mr_train_final.jsonl", read_jsonl(ROOT / "data/processed/uk/mr_train.jsonl") + read_jsonl(ext / "mr_non_benchmark.jsonl"))
    counts["lang_curriculum_external"] = write_jsonl(out / "lang_curriculum_external.jsonl", read_jsonl(ROOT / "data/processed/uk/lang_train.jsonl") + read_jsonl(ext / "monolingual_train.jsonl"))
    counts["format_polish_final"] = write_jsonl(out / "format_polish_final.jsonl", read_jsonl(ROOT / "data/processed/uk/format_preferences.jsonl"))
    return counts


def build_sorbian() -> dict[str, int]:
    out = ROOT / "data/processed/final/sorbian"
    ext = ROOT / "data/processed/external/sorbian"
    counts = {}
    counts["mt_train_final"] = write_jsonl(out / "mt_train_final.jsonl", read_jsonl(ROOT / "data/processed/sorbian/mt_train.jsonl", 120000) + read_jsonl(ext / "mt_prior_wmt.jsonl"))
    counts["qa_train_final"] = write_jsonl(out / "qa_train_final.jsonl", read_jsonl(ext / "qa_generated_public_hsb.jsonl") + read_jsonl(ext / "qa_generated_public_dsb.jsonl"))
    counts["sc_train_final"] = write_jsonl(out / "sc_train_final.jsonl", read_jsonl(ROOT / "data/processed/sorbian/sc_train.jsonl") + read_jsonl(ext / "sc_synthetic_hsb.jsonl") + read_jsonl(ext / "sc_synthetic_dsb.jsonl"))
    counts["gc_train_final"] = write_jsonl(out / "gc_train_final.jsonl", read_jsonl(ROOT / "data/processed/sorbian/gc_train.jsonl") + read_jsonl(ext / "gc_synthetic_hsb.jsonl") + read_jsonl(ext / "gc_synthetic_dsb.jsonl"))
    counts["mr_train_final"] = write_jsonl(out / "mr_train_final.jsonl", read_jsonl(ROOT / "data/processed/sorbian/mr_train.jsonl") + read_jsonl(ext / "mr_non_benchmark_hsb.jsonl") + read_jsonl(ext / "mr_non_benchmark_dsb.jsonl"))
    counts["lang_curriculum_external"] = write_jsonl(out / "lang_curriculum_external.jsonl", read_jsonl(ROOT / "data/processed/sorbian/lang_train.jsonl") + read_jsonl(ext / "monolingual_public.jsonl"))
    counts["format_polish_final"] = write_jsonl(out / "format_polish_final.jsonl", read_jsonl(ROOT / "data/processed/sorbian/format_preferences.jsonl"))
    return counts


def main() -> int:
    uk = build_uk()
    sorb = build_sorbian()
    summary = ROOT / "data/manifests/final_training_data_summary.md"
    lines = ["# Final Training Data Summary", "", "## Ukrainian", ""]
    for name, count in uk.items():
        lines.append(f"- `{name}`: {count}")
    lines.extend(["", "## Sorbian", ""])
    for name, count in sorb.items():
        lines.append(f"- `{name}`: {count}")
    lines.extend(["", "Generated by `scripts/build_external_training_sets.py`."])
    summary.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {summary}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
